/**
 * Centralized Permission Constants (Frontend)
 */
export const PERMISSIONS = {
  // LOTES
  LOTES_VIEW: 'LOTES_VIEW',
  LOTES_CREATE: 'LOTES_CREATE',
  LOTES_EDIT: 'LOTES_EDIT',
  LOTES_DELETE: 'LOTES_DELETE',
  LOTES_SALE: 'LOTES_SALE',
  LOTES_PHOTOS: 'LOTES_PHOTOS',
  LOTES_CATALOG: 'LOTES_CATALOG',
  LOTES_RELEASE: 'LOTES_RELEASE',

  // CLIENTES
  CLIENTES_VIEW: 'CLIENTES_VIEW',
  CLIENTES_CREATE: 'CLIENTES_CREATE',
  CLIENTES_DETAILS: 'CLIENTES_DETAILS',
  CLIENTES_EDIT: 'CLIENTES_EDIT',
  CLIENTES_CONTACT: 'CLIENTES_CONTACT',
  CLIENTES_EXPORT: 'CLIENTES_EXPORT',

  // PAGOS
  PAGOS_VIEW: 'PAGOS_VIEW',
  PAGOS_APPROVE: 'PAGOS_APPROVE',
  PAGOS_REJECT: 'PAGOS_REJECT',
  PAGOS_CREATE: 'PAGOS_CREATE',
  PAGOS_RECEIPT: 'PAGOS_RECEIPT',
  PAGOS_PORTAL: 'PAGOS_PORTAL',

  // CARTERA
  CARTERA_DASHBOARD: 'CARTERA_DASHBOARD',
  CARTERA_FOLLOWUP: 'CARTERA_FOLLOWUP',
  CARTERA_SUMMARY: 'CARTERA_SUMMARY',
  CARTERA_EXPORT: 'CARTERA_EXPORT',

  // BANCOS
  BANCOS_VIEW: 'BANCOS_VIEW',
  BANCOS_MANAGE: 'BANCOS_MANAGE',
  BANCOS_DELETE: 'BANCOS_DELETE',

  // EQUIPO
  EQUIPO_VIEW: 'EQUIPO_VIEW',
  EQUIPO_MANAGE: 'EQUIPO_MANAGE',
  EQUIPO_ROLES: 'EQUIPO_ROLES',
  EQUIPO_DELETE: 'EQUIPO_DELETE',

  // IMPORTACIÓN
  IMPORT_MANAGE: 'IMPORT_MANAGE',

  // CONFIG & IA
  IA_CHAT: 'IA_CHAT',
  CONFIG_TENANT: 'CONFIG_TENANT',
  CONFIG_SUPER: 'CONFIG_SUPER',

  // SISTEMA & AUDITORIA
  SYSTEM_LOGS: 'SYSTEM_LOGS',
  SYSTEM_AUDIT: 'SYSTEM_AUDIT',
  CATEGORIES_MANAGE: 'CATEGORIES_MANAGE',
  TRANSACCIONES_VIEW: 'TRANSACCIONES_VIEW',
  TRANSACCIONES_MANAGE: 'TRANSACCIONES_MANAGE',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * Role to Permission Mapping
 */
export const ROLE_PERMISSIONS: Record<string, Permission[] | string[]> = {
  superadmin: ['ALL'],
  
  tenant_admin: [
    ...Object.values(PERMISSIONS).filter(p => ![PERMISSIONS.CONFIG_SUPER, (PERMISSIONS as any).SYSTEM_LOGS].includes(p))
  ],

  company_admin: [
    ...Object.values(PERMISSIONS).filter(p => ![PERMISSIONS.CONFIG_SUPER, (PERMISSIONS as any).SYSTEM_LOGS].includes(p))
  ],

  vendedor: [
    PERMISSIONS.LOTES_VIEW,
    PERMISSIONS.LOTES_CREATE,
    PERMISSIONS.LOTES_EDIT,
    PERMISSIONS.LOTES_SALE,
    PERMISSIONS.LOTES_PHOTOS,
    PERMISSIONS.LOTES_CATALOG,
    PERMISSIONS.CLIENTES_VIEW,
    PERMISSIONS.CLIENTES_CREATE,
    PERMISSIONS.CLIENTES_DETAILS,
    PERMISSIONS.CLIENTES_EDIT,
    PERMISSIONS.CLIENTES_CONTACT,
    PERMISSIONS.PAGOS_VIEW,
    PERMISSIONS.PAGOS_CREATE,
    PERMISSIONS.PAGOS_RECEIPT,
    PERMISSIONS.PAGOS_PORTAL,
    PERMISSIONS.CARTERA_DASHBOARD,
    PERMISSIONS.CARTERA_SUMMARY,
    PERMISSIONS.IA_CHAT,
  ],

  agent: [
    PERMISSIONS.LOTES_VIEW,
    PERMISSIONS.LOTES_CATALOG,
    PERMISSIONS.CLIENTES_VIEW,
    PERMISSIONS.CLIENTES_DETAILS,
    PERMISSIONS.CLIENTES_CONTACT,
    PERMISSIONS.PAGOS_VIEW,
    PERMISSIONS.PAGOS_CREATE,
    PERMISSIONS.PAGOS_RECEIPT,
    PERMISSIONS.PAGOS_PORTAL,
    PERMISSIONS.CARTERA_DASHBOARD,
    PERMISSIONS.CARTERA_FOLLOWUP,
    PERMISSIONS.CARTERA_SUMMARY,
    PERMISSIONS.IA_CHAT,
  ],
  cliente: [
    PERMISSIONS.LOTES_VIEW,
    PERMISSIONS.PAGOS_VIEW,
    PERMISSIONS.PAGOS_CREATE,
    PERMISSIONS.CLIENTES_DETAILS,
  ],
};

/**
 * Utility to check permissions
 */
export const hasPermission = (role: string | undefined, permission: Permission): boolean => {
  if (!role) return false;
  const permissions = ROLE_PERMISSIONS[role] || [];
  return (permissions as any[]).includes(permission) || (permissions as any[]).includes('ALL');
};
